src/Entity/Adresse.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdresseRepository")
 */
class Adresse
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $type_voie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_voie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $cp;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Societe", inversedBy="adresses")
     */
    private $societe;

    public function __construct()
    {
        $this->societe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getTypeVoie(): ?string
    {
        return $this->type_voie;
    }

    public function setTypeVoie(string $type_voie): self
    {
        $this->type_voie = $type_voie;

        return $this;
    }

    public function getNomVoie(): ?string
    {
        return $this->nom_voie;
    }

    public function setNomVoie(string $nom_voie): self
    {
        $this->nom_voie = $nom_voie;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    /**
     * @return Collection|Societe[]
     */
    public function getSociete(): Collection
    {
        return $this->societe;
    }

    public function addSociete(Societe $societe): self
    {
        if (!$this->societe->contains($societe)) {
            $this->societe[] = $societe;
        }

        return $this;
    }

    public function removeSociete(Societe $societe): self
    {
        if ($this->societe->contains($societe)) {
            $this->societe->removeElement($societe);
        }

        return $this;
    }

    /**
     * Generates the magic method
     * 
     */
    public function __toString(){
        // to show the name of the Category in the select
        $adresseComplete = $this->numero. ", ".$this->type_voie. " ".$this->nom_voie. " - ".$this-> ville. " ".$this-> cp;
        return $adresseComplete;
        // to show the id of the Category in the select
        // return $this->id;
    }  
}

src/Entity/Societe.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiFilter;
use Doctrine\Common\Collections\Collection;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use ApiPlatform\Core\Serializer\Filter\PropertyFilter;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\SocieteRepository")
 * 
 * @ApiResource(
 *  collectionOperations={"get"},
 *  itemOperations={"get"},
 *  order={"date"="ASC"},
 *  paginationEnabled=false * 
 * )  * 
 * 
 * 
 * @ApiFilter(PropertyFilter::class)
 */


class Societe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $siren;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $ville_immat;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_immat;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=3)
     * @Assert\Positive
     */     
    private $capital;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\FormeJuridique", inversedBy="societes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $forme_juridique;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Adresse", mappedBy="societe")
     */
    private $adresses;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Historique", mappedBy="societe")
     */
    private $historiques;

    public $numeroAdr;

    public $typeVoieAdr;

    public $nomVoieAdr;

    public $villeAdr;

    public $cpAdr;



    public function __construct()
    {
        $this->adresses = new ArrayCollection();
        $this->historiques = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getSiren(): ?int
    {
        return $this->siren;
    }

    public function setSiren(int $siren): self
    {
        $this->siren = $siren;

        return $this;
    }

    public function getVilleImmat(): ?string
    {
        return $this->ville_immat;
    }

    public function setVilleImmat(string $ville_immat): self
    {
        $this->ville_immat = $ville_immat;

        return $this;
    }

    public function getDateImmat(): ?\DateTimeInterface
    {
        return $this->date_immat;
    }

    public function setDateImmat(\DateTimeInterface $date_immat): self
    {
        $this->date_immat = $date_immat;

        return $this;
    }

    public function getCapital(): ?string
    {
        return $this->capital;
    }

    public function setCapital(string $capital): self
    {
        $this->capital = $capital;

        return $this;
    }

    public function getFormeJuridique(): ?FormeJuridique
    {
        return $this->forme_juridique;
    }

    public function setFormeJuridique(?FormeJuridique $forme_juridique): self
    {
        $this->forme_juridique = $forme_juridique;

        return $this;
    }

    /**
     * @return Collection|Adresse[]
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdresse(Adresse $adresse): self
    {
       
        if (!$this->adresses->contains($adresse)) {
            $this->adresses[] = $adresse;
            $adresse->addSociete($this);
        }

        return $this;
    }

    public function removeAdresse(Adresse $adresse): self
    {
        if ($this->adresses->contains($adresse)) {
            $this->adresses->removeElement($adresse);
            $adresse->removeSociete($this);
        }

        return $this;
    }

    /**
     * @return Collection|Historique[]
     */
    public function getHistoriques(): Collection
    {
        return $this->historiques;
    }

    public function addHistorique(Historique $historique): self
    {
        if (!$this->historiques->contains($historique)) {
            $this->historiques[] = $historique;
            $historique->setSociete($this);
        }

        return $this;
    }

    public function removeHistorique(Historique $historique): self
    {
        if ($this->historiques->contains($historique)) {
            $this->historiques->removeElement($historique);
            // set the owning side to null (unless already changed)
            if ($historique->getSociete() === $this) {
                $historique->setSociete(null);
            }
        }

        return $this;
    }

    /**
     * Generates the magic method
     * 
     */
    public function __toString(){
        // to show the name of the Category in the select
        $nomSociete = $this->nom;
        return $nomSociete;
        // to show the id of the Category in the select
        // return $this->id;
    }     
}

src/Form/SocieteType.php
<?php

namespace App\Form;

use App\Entity\Societe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
class SocieteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class, array('required' => true,'label' => 'Nom/Raison sociale','attr' => ['html5' => false,],))
            ->add('siren', TextType::class, array('required' => true,'label' => 'SIREN','attr' => ['html5' => false,],))
            ->add('ville_immat', TextType::class, array('required' => true,'label' => 'Ville d\'immatriculation','attr' => ['html5' => false,],))
            ->add('date_immat', DateTimeType::class, array('required' => true,'widget' => 'single_text', 'label'=> 'Date d\'immatriculation'
                    ,'attr' => ['class' => 'form-control input-inline datetimepicker','data-provide' => 'datetimepicker','html5' => false,],))
            ->add('capital', TextType::class, array('required' => true,'label' => 'Capital','attr' => ['html5' => false,],))
            ->add('forme_juridique')
            ->add('numeroAdr', TextType::class, array('required' => true,'label' => 'Numéro','attr' => ['html5' => false,],))
            ->add('typeVoieAdr', TextType::class, array('required' => true,'label' => 'Type de voie','attr' => ['html5' => false,],))
            ->add('nomVoieAdr', TextType::class, array('required' => true,'label' => 'Nom de voie','attr' => ['html5' => false,],))
            ->add('villeAdr', TextType::class, array('required' => true,'label' => 'Ville','attr' => ['html5' => false,],))
            ->add('cpAdr', TextType::class, array('required' => true,'label' => 'Code postal','attr' => ['html5' => false,],))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Societe::class,
        ]);
    }
}

src/Controller/SocieteController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;

use App\Entity\Societe;
use App\Form\AdresseType;
use App\Form\SocieteType;
use App\Entity\Historique;
use App\Form\HistoriqueType;
use App\Form\SocieteDetailType;
use App\Event\SocieteActionEvent;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SocieteController extends AbstractController
{
    /**
     * @Route("/", name="societe_list")
     */
    public function index(Request $request, EventDispatcherInterface $eventDispatcher)
    {
        $societe = new Societe();
        $frmSociete = $this->CreateForm(SocieteType::class , $societe);

		if($request)
		{
        $frmSociete->handleRequest($request);
		   if($frmSociete->isSubmitted())
		   {
               // Instancier un objet adresse 
               $adresse = new Adresse();
                // Initialiser les attributs de l'objets avec les données du formulaire envoyé
               $adresse->setNumero($frmSociete->get('numeroAdr')->getData())
                        ->setTypeVoie($frmSociete->get('typeVoieAdr')->getData())
                        ->setNomVoie($frmSociete->get('nomVoieAdr')->getData())
                        ->setVille($frmSociete->get('villeAdr')->getData())
                        ->setCp($frmSociete->get('cpAdr')->getData());
                // Initialiser l'objet société parent avec l'objet adresse qui vient d'être créé
               $societe->addAdresse($adresse);
               $adresse->addSociete($societe);

               $event = new SocieteActionEvent ($societe, $adresse);
               $eventName = SocieteActionEvent::NAME;

               $entityManager = $this->getDoctrine()->getManager();

               $entityManager->persist($adresse);
               $entityManager->persist($societe);
               $entityManager->flush();
               $eventDispatcher->dispatch($eventName, $event);
			   return $this->redirectToRoute('societe_list');

		   }		
		}

		$repo = $this->getDoctrine()->getRepository(Societe::class);
        $societes = $repo->findAll();
		
		return $this->render('societe/index.html.twig', [
            'societes' => $societes,
            'frmSociete' => $frmSociete->createView(),
        ]);       

    }

    /**
     * @Route("societe/detail/{id}", name="societe_detail")
     */
    public function detailSociete(Request $request, Societe $societe, EventDispatcherInterface $eventDispatcher)
    {


        $frmSociete = $this->CreateForm(SocieteDetailType::class , $societe);
        if($request)
		{
        $frmSociete->handleRequest($request);
		   if($frmSociete->isSubmitted())
		   {
                $adresse = new Adresse(); 

                $idAdrDefaut = $request->request->get('idAdrDefaut');

                $adresse = $this->getDoctrine()
                ->getRepository(Adresse::class)
                ->find($idAdrDefaut);

               $societe->addAdresse($adresse);
               $adresse->addSociete($societe);

               $event = new SocieteActionEvent ($societe, $adresse);
               $eventName = SocieteActionEvent::NAME;

               $entityManager = $this->getDoctrine()->getManager();
               
               $entityManager->persist($adresse);
               $entityManager->persist($societe);
               $entityManager->flush();
               $eventDispatcher->dispatch($eventName, $event);
			   return $this->redirectToRoute('societe_list');

		   }		
		}         
       
        
        $adresse = new Adresse();
        $adresses = $societe->getAdresses();
        $adresse->addSociete($societe);
        $frmAdresse = $this->CreateForm(AdresseType::class , $adresse, ['action' => $this->generateUrl('adresse_add')]);

        $historique = new Historique();
        $historique->setSociete($societe);

        $frmHistorique = $this->CreateForm(HistoriqueType::class , $historique, ['action' => $this->generateUrl('historique')]);

        return $this->render('societe/detail.html.twig', [
            'frmSociete' => $frmSociete->createView(),
            'frmAdresse' => $frmAdresse->createView(),
            'frmHistorique' => $frmHistorique->createView(),
            'societe'=>$societe,
            'adresses'=> $adresses,
        ]);    


    }

    /**
     * @Route("societe/{id}/delete", name="societe_delete", methods={"POST"})
     */
    public function delete(Request $request, Societe $societe): Response
    {
        if ($this->isCsrfTokenValid('delete'.$societe->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($societe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('societe_list');
    }
}

templates/societe/detail.html.twig
{% extends 'base.html.twig' %}

{% form_theme frmSociete 'bootstrap_4_layout.html.twig' %}
{% form_theme frmAdresse 'bootstrap_4_layout.html.twig' %}
{% form_theme frmHistorique 'bootstrap_4_layout.html.twig' %}

{% block body %}

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">{{societe.nom}}</h1>
<div class="row">
        {{ form_start(frmHistorique)}}
        <div class="input-group mr-2">
        <div class="input-group-prepend">
            <button class="btn btn-primary" type="submit">Consulter l'historique</button>
        </div>
        {{ form_widget(frmHistorique)}}
        <input type="hidden" name="idSoc" id="idSoc" value="{{societe.id}}">       
       
        </div>
        {{ form_end(frmHistorique)}}    

</div>


	<div class="btn-toolbar mb-2 mb-md-0">
	  <div class="btn-group mr-2">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Ajouter une adresse</button>
	  </div>    
	</div>
  </div>
{{ form_start(frmSociete)}}
<div class="row">
    <div class="col-md-4">{{ form_row(frmSociete.siren, {'attr':{'readonly':true}})}}</div>
    <div class="col-md-4">{{ form_row(frmSociete.date_immat, {'attr':{'readonly':true}})}}</div>
    <div class="col-md-4">{{ form_row(frmSociete.ville_immat, {'attr':{'readonly':true}})}}</div>
</div>
    
<div class="row">
    <div class="col-md-4">{{ form_row(frmSociete.nom)}}</div>
    <div class="col-md-4">{{ form_row(frmSociete.capital)}}</div>
    <div class="col-md-4">{{ form_row(frmSociete.forme_juridique)}}</div>
</div>

<div class="row">
    <div class="col-md-4"></div>
    {% set adresse = adresses.first() %}
     <input type="hidden" name="idAdrDefaut" id="idAdrDefaut" value="{{adresse.id}}">
    <div class="col-md-4"><button type="submit" class="btn btn-primary" id="btnModif">Modifier</button></div>
    <div class="col-md-4"></div>
</div>
      
{{ form_end(frmSociete)}}  

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>#</th>
            <th>Adresse</th>
        </tr>
        </thead>
        <tbody>
        {% for adress in adresses %}
        <tr>
            <td>{{adress.id}}</td>
            <td>{{adress.numero}}  {{adress.typeVoie}}  {{adress.nomVoie}}  {{adress.ville}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">


        <h5 class="modal-title" id="exampleModalLabel">Créer une société</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {{ form_start(frmAdresse)}}
      <div class="modal-body">
            {{ form_widget(frmAdresse)}}
            <input type="hidden" name="idSocAdr" id="idSocAdr" value="{{societe.id}}">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
        <button type="submit" class="btn btn-primary" id="btnCreer">Créer</button>
      </div>
    {{ form_end(frmAdresse)}}  
    </div>
  </div>
</div>

{% endblock %}

templates/societe/index.html.twig
{% extends 'base.html.twig' %}
{% form_theme frmSociete 'bootstrap_4_layout.html.twig' %}
{% block body %}

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
	<h1 class="h2">Societes</h1>
	<div class="btn-toolbar mb-2 mb-md-0">
	  <div class="btn-group mr-2">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Créer une société</button>
	  </div>
	</div>
  </div>
{#  <div id="frmAjoutEvent" style="display:none;">
  
  
	{{ form_start(frmSociete)}}
	{{ form_widget(frmSociete)}}
	<button type="submit" class="btn btn-primary">Créer</button>
	{{ form_end(frmSociete)}}  
  
  </div>#}
<div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>#</th>
                  <th>Nom/Raison sociale</th>
                  <th>Date d'immatriculation</th>
                  <th>SIREN</th>
                  <th>Ville d'immatriculation</th>
                  <th>Capital</th>
                </tr>
              </thead>
              <tbody>
			  {% for societe in societes %}
                <tr>
                  <td>
                    <a href="{{path('societe_detail', {id : societe.id})}}"><span data-feather="edit"></span></a>
                    <!-- Formulaire de suppression d'une société à réactiver après correction des contraintes en BD
                    <form method="post" id="deleteFrm" action="{{ path('societe_delete', {'id': societe.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer cette société?');">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ societe.id) }}">
                        <span data-feather="trash" id="deleteBtn"></span>
                    </form>
                    -->
                  </td>
                  <td>{{societe.id}}</td>
                  <td>{{societe.nom}}</td>
                  <td>{{societe.dateImmat|date('d/m/Y h:m:s')}}</td>
                  <td>{{societe.siren}}</td>
                  <td>{{societe.villeImmat}}</td>
                  <td>{{societe.capital}}</td>
                </tr>
			   {% endfor %}
              </tbody>
            </table>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Créer une société</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {{ form_start(frmSociete)}}
      <div class="modal-body">
            {{ form_widget(frmSociete)}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
        <button type="submit" class="btn btn-primary" id="btnCreer">Créer</button>
      </div>
    {{ form_end(frmSociete)}}  
    </div>
  </div>
</div>

{% endblock %}